<?php
namespace Phptop50;

class HtmlTemplate
{
    public function render(array $pl): string
    {
        $title = "PHP GitHub top50 · 第{$pl['week']}期 ({$pl['year']})";
        $css   = $this->css();
        $body  = $this->body($pl);
        return "<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<meta name=viewport content='width=device-width,initial-scale=1'>
<title>{$title}</title>
<style>{$css}</style>
</head>
<body>
{$body}
</body>
</html>";
    }

    private function css(): string
{
    return '
    /* ----- 2006 原版 ----- */
    body{margin:0;background:#e2e2e2;font:12px/1.5 Verdana,Arial;color:#333}
    a{color:#036;text-decoration:none}
    a:hover{text-decoration:underline}
    #wrap{width:96%;max-width:900px;margin:20px auto;background:#fff;border:1px solid #999}
    #head{background:#669;color:#fff;padding:15px;font-size:18px;font-weight:bold}
    #bar{background:#99c;padding:4px 15px;font-size:11px;color:#fff}
    #cont{padding:15px}
    table.list{width:100%;border-collapse:collapse}
    table.list th{background:#ddd;padding:6px;text-align:left;font-size:11px;border:1px solid #bbb}
    table.list td{border:1px solid #ddd;padding:6px}
    tr.even{background:#f6f6f6}
    .topic{display:inline-block;background:#ddd;border:1px solid #bbb;padding:1px 4px;margin:1px;font-size:10px}
    #foot{text-align:center;padding:10px;font-size:10px;color:#666;background:#eee;border-top:1px solid #ccc}

    /* ----- 移动端能看就行 ----- */
    @media (max-width:600px){
        body{font-size:14px}                 /* 全局字号放大 */
        #wrap{width:100%;margin:10px 0;border-width:1px 0}
        #head{font-size:16px;padding:10px}
        #bar{padding:4px 10px}
        #cont{padding:10px 5px}

        /* 把表格变卡片 */
        table.list,table.list thead,table.list tbody,table.list th,table.list td{display:block}
        table.list thead{display:none}       /* 隐藏表头 */
        table.list tr{
            margin:0 0 8px 0;
            padding:6px;
            background:#fff;
            border:1px solid #bbb;
            position:relative;
        }
        tr.even{background:#fff}             /* 统一白底 */
        table.list td{
            border:none;
            padding:4px 6px;
            font-size:13px;
            line-height:1.4;
        }
        /* 用伪元素补字段名 */
        table.list td:nth-of-type(1):before{content:"# ";font-weight:bold;color:#669}
        table.list td:nth-of-type(2):before{content:"仓库: ";font-weight:bold;color:#669}
        table.list td:nth-of-type(3):before{content:"描述: ";font-weight:bold;color:#669}
        table.list td:nth-of-type(4):before{content:"⭐ Stars: ";font-weight:bold;color:#669}
        table.list td:nth-of-type(5):before{content:"🍴 Forks: ";font-weight:bold;color:#669}
        table.list td:nth-of-type(6):before{content:"话题: ";font-weight:bold;color:#669}
        .topic{font-size:11px;margin:2px}
    }
    ';
}


    private function body(array $pl): string
    {
        $h = "<div id=wrap>";
        $h .= "<div id=head>🐘 PHP GitHub top50 · 第{$pl['week']}期 ({$pl['year']})</div>";
        $h .= "<div id=bar>发布日期：{$pl['date']} · 排序：Star 数</div>";
        $h .= "<div id=cont>";
        $h .= "<table class=list><thead><tr><th>#</th><th>仓库</th><th>描述</th><th>Stars</th><th>Forks</th><th>话题</th></tr></thead><tbody>";
        $even = false;
        foreach ($pl['list'] as $r) {
            $cls = $even ? 'even' : '';
            $even = !$even;
            $topics = '';
            foreach ($r['topics'] as $t) $topics .= "<span class=topic>{$t}</span> ";
            $h .= "<tr class={$cls}>
                <td>{$r['rank']}</td>
                <td><a href='{$r['url']}' target=_blank>{$r['name']}</a></td>
                <td>{$r['desc']}</td>
                <td>{$r['star']}</td>
                <td>{$r['fork']}</td>
                <td>{$topics}</td>
            </tr>";
        }
        $h .= "</tbody></table></div>";
        $h .= "<div id=foot>Generated by GitHub Actions · " . date('Y-m-d H:i') . "</div>";
        $h .= "</div>";
        return $h;
    }
}