name: Weekly PHP Top10

on:
  schedule:
    - cron: '0 0 * * 1'      # 每周一 00:00 UTC
  workflow_dispatch:         # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-dev

      - name: Crawl & generate top10
        run: php src/crawler.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push changes
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Weekly update $(date +%Y%m%d)"
          git push

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(date +%Y%m%d)
          name: PHP Top10 Week $(date +%W)
          body_path: releases/top10-$(date +%Y-W%W).md
          files: releases/top10-$(date +%Y-W%W).md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
